[package]
name = "factor-client"
version.workspace = true
edition.workspace = true

[dependencies]
bevy.workspace = true
bevy_egui = { version = "0.30.0", default-features = false, features = ["default_fonts", "render"] }