[package]
name = "factor"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.14.2"
bytemuck = { version = "1.19.0", features = ["derive", "extern_crate_std"] }
cdshealpix = "0.7.0"
itertools = "0.13.0"
ordered-float = "4.5.0"
rand = "0.8.5"
rand_distr = "0.4.3"
redb = "2.2.0"
tinyset = "0.5.1"

[dev-dependencies]
bevy_egui = { version = "0.30.0", default-features = false, features = ["render", "default_fonts"]}