[package]
name = "factor"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.14.2"
bytemuck = { version = "1.19.0", features = ["derive", "extern_crate_std"] }
cdshealpix = "0.7.0"
itertools = "0.13.0"
rand = "0.8.5"
rand_distr = "0.4.3"
redb = "2.1.4"
tinyset = { version = "0.5.0", git = "https://github.com/matt-cornell/tinyset" }
