[package]
name = "factor"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
bevy = "0.14.2"
bytemuck = { version = "1.19.0", features = ["derive", "extern_crate_std"] }
cdshealpix = "0.7.0"
itertools = "0.13.0"
ordered-float = "4.5.0"
rand = "0.8.5"
rand_distr = "0.4.3"
redb = "2.2.0"
serde = { version = "1.0.214", features = ["derive"] }
tinyset = "0.5.1"
toml = "0.8.19"

[dev-dependencies]
bevy_egui = { version = "0.30.0", default-features = false, features = ["default_fonts", "render"] }
rfd = "0.15.0"

[target.'cfg(target_family = "wasm")'.dependencies]
wasm-bindgen = "0.2.95"
web-sys = { version = "0.3.72", features = ["console", "Document", "Storage", "Window"] }
web-time = "1.1.0"

[target.'cfg(not(target_family = "wasm"))'.dependencies]
etcetera = "0.8.0"

[target.'cfg(unix)'.dependencies]
libc = "0.2.162"