[package]
name = "factor-common"
version.workspace = true
edition.workspace = true

[dependencies]
async-trait.workspace = true
bevy.workspace = true
cdshealpix.workspace = true
postcard.workspace = true
serde.workspace = true

[lints]
workspace = true
