name: Deploy site

on:
  push:
    branches: ["main"]

env:
  client_examples: surface
  server_examples: terrain
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: --cfg getrandom_backend="wasm_js"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Rust
        run: rustup target add wasm32-unknown-unknown
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
      - name: Install wasm-bindgen
        run: cargo install wasm-bindgen-cli
      - name: Build server examples
        run: cargo build --target wasm32-unknown-unknown --profile github-release -p factor-server $(echo $server_examples | sed 's/[^ ]* */--example &/g')
      - name: Build client examples
        run: cargo build --target wasm32-unknown-unknown --profile github-release -p factor-client $(echo $client_examples | sed 's/[^ ]* */--example &/g')
      - name: Build web demos
        run: cargo build --target wasm32-unknown-unknown --profile github-release -p factor -p factor-client
      - name: Create bindings
        run: |
          mkdir -p static-deployment/examples/
          for name in $client_examples $server_examples; do
            wasm-bindgen --no-typescript --target no-modules --out-dir static-deployment/examples target/wasm32-unknown-unknown/github-release/examples/$name.wasm
            cp static-deployment/_base_example.html static-deployment/examples/$name.html
          done
          mv target/wasm32-unknown-unknown/github-release/factor.wasm web-demo.wasm
          mv target/wasm32-unknown-unknown/github-release/factor-client.wasm client.wasm
          wasm-bindgen --no-typescript --target no-modules --out-dir static-deployment web-demo.wasm
          wasm-bindgen --no-typescript --target no-modules --out-dir static-deployment client.wasm
          cp static-deployment/_base_example.html static-deployment/web-demo.html
          cp static-deployment/_base_example.html static-deployment/client.html
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: static-deployment/
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
