name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  native:
    runs-on: ubuntu-latest
    steps:
      - name: Install system libraries
        run: sudo apt install -y libasound2-dev libudev-dev libwayland-dev
      - uses: actions/checkout@v4
      # - name: Run tests
      #   run: cargo test
      - name: Check with clippy
        run: cargo clippy
  wasm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install WASM target
        run: rustup target add wasm32-unknown-unknown
      - name: Check with clippy
        run: cargo clippy --target wasm32-unknown-unknown
